# permissions for end users to edit coredns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredns-editor-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - coredns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - coredns/status
  verbs:
  - get
