# permissions for end users to view coredns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredns-viewer-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - coredns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - coredns/status
  verbs:
  - get
