apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-role
rules:
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - subjectaccessreviews
  verbs: ["create"]
- apiGroups: ["apps"]
  resources:
  - "daemonsets"
  verbs: ["create", "get", "watch", "update"]
- apiGroups: [""]
  resources:
  - "configmaps"
  - "serviceaccounts"
  verbs: ["create", "get", "watch", "update"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - "clusterrolebindings"
  - "clusterroles"
  verbs: ["create", "get", "watch", "update"]
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
