# permissions to do edit flannels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flannel-editor-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - flannels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - flannels/status
  verbs:
  - get
  - patch
  - update
