apiVersion: addons.x-k8s.io/v1alpha1
kind: Flannel
metadata:
  name: flannel-sample
  namespace: kube-system
spec:
  channel: stable
  patches:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kube-flannel-cfg
      namespace: kube-system
    data:
      net-conf.json: |
        {
          "Network": "10.0.0.0/8",
          "SubnetLen": 20,
          "SubnetMin": "10.10.0.0",
          "SubnetMax": "10.99.0.0",
          "Backend": {
            "Type": "udp",
            "Port": 7890
          }
        }
