# permissions to do edit nodelocaldns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodelocaldns-editor-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - nodelocaldns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - nodelocaldns/status
  verbs:
  - get
  - patch
  - update
