# permissions to do viewer nodelocaldns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodelocaldns-viewer-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - nodelocaldns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - nodelocaldns/status
  verbs:
  - get
