apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-role
rules:
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - subjectaccessreviews
  verbs: ["create"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["events", "serviceaccounts"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["apps", "extensions"]
  resources: ["daemonsets"]
  verbs: ["get", "watch", "list", "create", "patch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["app.k8s.io"]
  resources: ["applications"]
  verbs: ["get", "watch", "list", "create", "patch"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["list", "watch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
