# permissions to do edit generics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: generic-editor-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  # <--------
  - generics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - generics/status
  verbs:
  - get
  - patch
  - update
