# permissions to do viewer generics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: generic-viewer-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - generics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - generics/status
  verbs:
  - get
