# permissions to do edit localnodedns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localnodedns-editor-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - localnodedns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - localnodedns/status
  verbs:
  - get
  - patch
  - update
